Release engineering of select_gpu: Several error checks, and additional tests in the Makefile.

diff --git a/src/Makefile b/src/Makefile
--- a/src/Makefile
+++ b/src/Makefile
@@ -28,8 +28,44 @@ test : test_select_gpu
 
 test_select_gpu : $(BUILDBINDIR)/select_gpu
 	@echo "Testing select_gpu..."
+	@# Test 1
 	@buildbindir=$(BUILDBINDIR) ; \
-	if [ "$$(ROCR_VISIBLE_DEVICES= SLURM_LOCALID=200 $${buildbindir}/select_gpu env | grep ROCR_VISIBLE_DEVICES)" = "ROCR_VISIBLE_DEVICES=200" ] ; \
-	    then echo "Test of select_gpu succeeded" ; \
-	    else echo "Test of select_gpu failed" ; exit 1 ; \
+	if [ "$$(ROCR_VISIBLE_DEVICES= SLURM_LOCALID=1 $${buildbindir}/select_gpu env | grep ROCR_VISIBLE_DEVICES)" = "ROCR_VISIBLE_DEVICES=1" ] ; \
+	    then echo "Test 1 of select_gpu succeeded" ; \
+	    else echo "Test 1 of select_gpu failed" ; exit 1 ; \
 	fi
+	@# Test 2: Check if ROCR_VISIBLE_DEVICES is overwritten with the correct value.
+	@buildbindir=$(BUILDBINDIR) ; \
+	if [ "$$(ROCR_VISIBLE_DEVICES=2 SLURM_LOCALID=1 $${buildbindir}/select_gpu env | grep ROCR_VISIBLE_DEVICES)" = "ROCR_VISIBLE_DEVICES=1" ] ; \
+	    then echo "Test 2 of select_gpu succeeded" ; \
+	    else echo "Test 2 of select_gpu failed" ; exit 1 ; \
+	fi
+	@# Test 3: We should get an error return in this case as SLURM_LOCALID is empty.
+	@buildbindir=$(BUILDBINDIR) ; \
+	SLURM_LOCALID= $${buildbindir}/select_gpu env >& /dev/null ; \
+	if [ $$? -ne 0 ] ; \
+		then echo "Test 3 of select_gpu succeeded" ;  \
+		else echo "Test 3 of select_gpu failed" ; exit 1 ; \
+	fi
+	@# Test 4: We should get an error return in this case as SLURM_LOCALID is a negative number.
+	@buildbindir=$(BUILDBINDIR) ; \
+	SLURM_LOCALID=-1 $${buildbindir}/select_gpu env >& /dev/null ; \
+	if [ $$? -ne 0 ] ; \
+		then echo "Test 4 of select_gpu succeeded" ;  \
+		else echo "Test 4 of select_gpu failed" ; exit 1 ; \
+	fi
+	@# Test 5: We should get an error return in this case as SLURM_LOCALID is a not a number.
+	@buildbindir=$(BUILDBINDIR) ; \
+	SLURM_LOCALID=1a $${buildbindir}/select_gpu env >& /dev/null ; \
+	if [ $$? -ne 0 ] ; \
+		then echo "Test 5 of select_gpu succeeded" ;  \
+		else echo "Test 5 of select_gpu failed" ; exit 1 ; \
+	fi
+	@# Test 6: Check if select_gpu fails in the expected way when no arguments are given.
+	@buildbindir=$(BUILDBINDIR) ; \
+	$${buildbindir}/select_gpu |& grep -q file-to-exec ; \
+	if [ $$? -eq 0 ] ; \
+		then echo "Test 6 of select_gpu succeeded" ;  \
+		else echo "Test 6 of select_gpu failed" ; exit 1 ; \
+	fi
+
